### ISSUE TITLE
Creazione Utente

### ISSUE THREAD

**Issue by lrgazzella** [frtrotta/app-registrazione#9]
Nella creazione di un utente, con corpo della richiesta `{"password":"prova","gettoneAutenticazione":null,"gettoneAutenticazioneScadeIl":null,"nome":"prova","cognome":"prova","sesso":"M","natoIl":"1995/06/12","email":"prova@gmail.com","telefono":"01234567890","eAmministratore":false,"facebookId":null}`, il server risponde con l'errore `Incoherent data. The data you provided did not meet expectations: please checkt and try again.`

**Comment by frtrotta** [comment]
Fixed in the latest release

**Comment by lrgazzella** [comment]
Creando un nuovo utente senza specificare il campo id, il server risponde ancora con l'errore `Incoherent data. The data you provided did not meet expectations: please checkt and try again.`

**Comment by frtrotta** [comment]
If the issue has not been solved yet, do not forget to reopen it.

Besides the misprint ("checkt"), the problem is not caused by the missing. Indeed one of the tests (#52) consists in a POST request with the JSON body `{"password":"prova","gettoneAutenticazione":null,"gettoneAutenticazioneScadeIl":null,"nome":"prova","cognome":"prova","sesso":"M","natoIl":"1995/06/12","email":"delete_prova@gmail.com","telefono":"01234567890","eAmministratore":false,"facebookId":null}`

The request succeeds.

Check your code again or post your request here.

**Comment by lrgazzella** [comment]
Tutte le date devono avere il formato `yyyy/MM/dd` o `yyyy-MM-dd` (secondo la definizione di formato del filtro `date` di AngularJS)
